/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.acquire;

import org.junit.jupiter.api.Test;
import org.testng.junit.JUnitTestRunner;


import javax.xml.transform.Result;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
<<<<<<< HEAD

=======
    public static void main(String[] args){
        JUnitTestRunner junit = new JUnitTestRunner();

        //junit.run(CorporationTest.class);
    }
>>>>>>> release/v1.0.0
}
