/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.acquire;

import org.junit.jupiter.api.Test;
import org.testng.junit.JUnitTestRunner;


import javax.xml.transform.Result;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    public static void main(String[] args){

    }
}
